# test_happy_path.py

from io import BytesIO
from keras.models import load_model
from model import preprocess_img, predict_result
from app import app
import pytest


@pytest.fixture
def client():
    """
    Fixture for the Flask test client.
    - Purpose: Set up a test client for making requests to the Flask app during testing.
    - Usage: Provides a `client` object to use for HTTP request simulations.
    """
    with app.test_client() as client:
        yield client

@pytest.fixture(scope="module")
def model():
    """
    Fixture for the Flask test model.
    - Purpose: Set up a test model to ensure it conducts the correct analysis.
    - Usage: Provides a `model` object to use for image recognition.
    """
    model = load_model("digit_model.h5")
    return model

def test_client_full_expected_path(model, client):
    """
    Test Case: Client File Uploaded to Digits Corrrectly Recognized
    - Author: Dylan
    - Purpose: Validate the application conducts it's functional requirements correctly when given the expected information.
    - Scenario:
        - Simulate a POST request to the `/prediction` route with correct image file data.
        - Assert the response status code is 200 (to indicate a valid request was processed).
        - Checks the image with the base model to get a digit output.
        - Verify that the response includes a prediction and the prediction is the expected number given the uploaded image
        - Verify that the prediction number matches the one generated by the model fixture.
    """
    img_path = "test_images/4/Sign 4 (46).jpeg"
    processed_img = preprocess_img(img_path) # Setup model with image
    model_prediction = predict_result(processed_img) # Get model's preduction (should be 4)
    assert model_prediction == 4 # Asserting that the model's functionality is correct

    with open(img_path, "rb") as img:
        response = client.post(
            "/prediction",
            data={"file": (img, "Sign 4 (46).jpeg")},
            content_type="multipart/form-data"
        )

    # Asserting that the apps functionality is correct
    assert response.status_code == 200
    assert b"Prediction" in response.data
    assert b"4" in response.data # Explicitly checking for a 4
    assert str(model_prediction).encode() in response.data # Implicitly checking for a 4
