name: Locust Load Testing

on:
  workflow_run:
    workflows: [Flask Image Recognition build and install]
    types:
      - completed


jobs:

  load-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Start Flask Application
      run: |
        python app.py &
        sleep 10  # Wait for app to start
      env:
        FLASK_ENV: testing

    - name: Run Locust Load Test
      run: |
        mkdir -p results
        locust -f locustfile.py --headless --users 10 --spawn-rate 1 --run-time 30s --host http://localhost:9000 --loglevel INFO --csv results/locust_stats

    - name: Upload Locust Results
      uses: actions/upload-artifact@v4
      with:
        name: locust-results
        path: results
